### PR TITLE
fix: license validation

### PR DESCRIPTION
**Pull request by Girgetto**
### Main changes

- :bug: (bug solved) 

To solve the problems related to #21 #20 I've added a new function `checkIfLicenseAreCorrect`, to check if the licenses inserted with `--failOn` flag are valid.

To check whether a license is a good one or not, I've created a list of correct `licenses`in `./utils`, if the license insert by users is included in the list can pass, otherwise it will be tested with a regex, **with insesitive case**,  to check if a good license could be found.

_Ex._
A user run `npx @guidesmiths/license-checker --failOn  apache`, apache is not a good license, so when `getAllCorrectLicenses` it's executed it will return `apache,Apache-1.0,Apache-2.0` which are 2 correct licenses.

If user execute `npx @guidesmiths/license-checker --failOn  Apache-1.0`, Apache-1.0 is a good license, so the algorithm will return `Apache-1.0`

_**What happens if a good license is missing from the array?**_

`checkIfLicenseAreCorrect ` don't remove licenses added by users, it just adds those who are correct.

### Context

- #21  :ticket: 
- #20  :ticket:

### CODE REVIEW

**Comment by s1mrankaur** [comment]
@inigomarquinez  Is there a way to use RegExp yet?

**Comment by Girgetto** [comment]
@s1mrankaur you need to run `npx @guidesmiths/license-checker --failOn LICENSE-TO-CHECK`

**Comment by Girgetto** [comment]
> @Girgetto Thanks for your prompt response. Any plans to make this an npm package?

This is already a npm package [license-checker](https://www.npmjs.com/package/@guidesmiths/license-checker)

**Comment by s1mrankaur** [comment]
@Girgetto  I tried  npx @guidesmiths/license-checker --summary --failOn Apache
├─ MIT: 1551
├─ ISC: 213
├─ Apache-2.0: 175
├─ BSD-3-Clause: 58
├─ BSD-2-Clause: 34
├─ UNLICENSED: 17
├─ MIT*: 9
├─ (MIT OR CC0-1.0): 5
├─ Artistic-2.0: 3
├─ Unlicense: 3
├─ BSD*: 3
├─ (MIT OR Apache-2.0): 2
├─ Apache 2.0: 2
├─ (Unlicense OR Apache-2.0): 1
├─ Custom: https://github.com/aws-amplify/amplify-js: 1
├─ Python-2.0: 1
├─ Custom: http://github.com/substack/node-bufferlist: 1
├─ CC-BY-4.0: 1
├─ (MIT OR WTFPL): 1
├─ AFLv2.1,BSD: 1
├─ (MIT OR GPL-3.0-or-later): 1
├─ (WTFPL OR MIT): 1
├─ EPL-1.0: 1
├─ (MIT AND Zlib): 1
├─ (BSD-2-Clause OR MIT OR Apache-2.0): 1
├─ (MIT AND BSD-3-Clause): 1
├─ CC-BY-3.0: 1
├─ CC0-1.0: 1
├─ (MIT AND CC-BY-3.0): 1
└─ 0BSD: 1

This did not fail. 

But 
 npx @guidesmiths/license-checker --summary --failOn Apache-2.0
Found license defined by the --failOn flag: "Apache-2.0". Exiting.

so unless the license name is EXACT, it does not seem to be failing

**Pull request merged**
