### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by inigomarquinez**
### Main changes

- chore: update README with usage instructions
- chore: increment patch version

### CODE REVIEW

**Comment by inigomarquinez** [comment]
@all-contributors please add @jmtorralvo for code,doc,ideas,maintenance,review

**Comment by inigomarquinez** [comment]
@all-contributors please add @MarioQuiroga32 for code,doc,ideas,maintenance,review

**Comment by inigomarquinez** [comment]
@all-contributors please add @inigomarquinez for code,doc,ideas,maintenance,review

**Comment by inigomarquinez** [comment]
@all-contributors please add @jmtorralvo for code, doc, ideas, maintenance, review

**Comment by inigomarquinez** [comment]
@all-contributors please add @MarioQuiroga32 for code, doc, ideas, maintenance, review

**Comment by inigomarquinez** [comment]
@all-contributors please add @inigomarquinez  for code, doc, ideas, maintenance, review

**Review by MarioQuiroga32 — APPROVED** [review]

**Review by jmtorralvo — APPROVED** [review]
LGTM!

**Pull request merged**
